name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract VERUS_VERSION
        id: extract
        run: |
          version=$(grep '^ARG VERUS_VERSION=' .devcontainer/Dockerfile | cut -d'=' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and verify the example project
        uses: devcontainers/ci@v0.3
        with:
          push: always
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          imageTag: ${{ steps.extract.outputs.version }},${{ github.sha }},latest
          runCmd: cargo build && cargo verus check
