name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: cargo build && cargo verus check
