name: Update Verus Version

on:
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:

jobs:
  update-verus-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Verus release
        id: verus
        run: |
          latest=$(curl -s https://api.github.com/repos/verus-lang/verus/releases/latest | jq -r .tag_name | sed 's|release/||')
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Update Dockerfile VERUS_VERSION
        run: |
          sed -i "s|^ARG VERUS_VERSION=.*|ARG VERUS_VERSION=${{ steps.verus.outputs.latest }}|" .devcontainer/Dockerfile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update VERUS_VERSION to ${{ steps.verus.outputs.latest }}"
          branch: "update/verus-version-${{ steps.verus.outputs.latest }}"
          title: "Update VERUS_VERSION to ${{ steps.verus.outputs.latest }}"
          body: "Automated update to the latest Verus release."
